### ISSUE TITLE
Provide block latency data in squid

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#13]
## Context
For monitoring purposes, we want to be able to query data about the average block latency from our squids. 

## TODO
Instead of only considering the latency of the last produced block, we want to query the average block latency over some number of blocks. This number should be a configurable variable, and we will set it to 20 for now, such that the latency of the last 20 blocks is considered. 
To calculate the block latency, on every new block, we should query the on-chain storage of [Timestamp.Now](https://github.com/pendulum-chain/pendulum-squids/blob/121c88a26dbbe10e64551129196797cb4e561ff6/typegen-foucoco.json#L39) and compare it to the timestamp of the last block. 
To achieve this we would need to: 
- On every block, store the timestamp of the current block (given by `Timestamp.Now`)
- Compare this timestamp to the last stored timestamp to calculate the latency of the last block. Store that latency in some kind of FIFO structure that is able to hold 20 items. This structure is of course not readily available but the implementation we do should behave that way, ie. it should drop timestamp items that are older than 20 blocks.

I would suggest something like the following schema. The naming etc can still be improved but I would imagine it to look similar:
```graphql
type TimeStamp @entity {
  id: ID!
  blockNumber: BigInt!
  timestamp: DateTime!
}

type LatencyInfo @entity {
   last20Blocks: [TimeStamp!]! // we store the timestamp data of the last 20 blocks in this attribute
   averageLatency: BigInt! // This is calculated based on the `last20Blocks`, but we have to add it to this entity here so that it's easier to query
}
```

**Comment by ebma** [comment]
@pendulum-chain/product I created this ticket as it is required to solve [this](https://github.com/pendulum-chain/tasks/issues/56) issue ticket. I'm not sure which epic I should assign it to.

**Comment by vadaynujra** [comment]
@ebma @prayagd should we have an epic regarding Devops enhancements or similar and assign such tickets to it?

**Comment by ebma** [comment]
Uhm yeah sure, we could do something like that. But this epic would then go on forever, not sure if that's a problem?

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/13?planning-poker) with Zenhub @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by prayagd** [comment]
@ebma if this is not urgent should i move this to icebox?

**Comment by ebma** [comment]
Since this ticket is required for https://github.com/pendulum-chain/tasks/issues/56 I'd only move it to the icebox if you think that https://github.com/pendulum-chain/tasks/issues/56 is not important right now.

**Comment by prayagd** [comment]
@ebma i assume this would indirectly help in the determining the inactive collators right? If yes then i would keep this here

**Comment by ebma** [comment]
Yes 👍

**Comment by TorstenStueber** [comment]
@prayagd I think that this ticket is fairly important and should not be moved to icebox but should be prioritized instead.

**Comment by TorstenStueber** [comment]
@prayagd can we move this to Ready then?

**Comment by ebma** [comment]
Let's also close this ticket as the one it was required for was closed https://github.com/pendulum-chain/tasks/issues/56#issuecomment-1864042489.

**Comment by TorstenStueber** [comment]
Sure, then we can actually close it.
