### ISSUE TITLE
Create squid (indexer) for Pendulum network

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#14]
So far we only have squids for Amplitude and Foucoco. Since we want to launch Nabla on Pendulum soon, we will need to have an indexer for Pendulum as well. 

Thus, we should create a pendulum-squid that has the same functionalities as the others
- Add pendulum to the [config](https://github.com/pendulum-chain/pendulum-squids/blob/main/src/config.ts) file
- Create a `squid-pendulum.yaml` file, similar to the others
- Create a `typegen-pendulum.json` file, similar to the others
- Add `process:pendulum` and `typegen:pendulum` to the [commands](https://github.com/pendulum-chain/pendulum-squids/blob/main/commands.json)
- Generate and use the pendulum-specific types
- Deploy it to aquarium

**Comment by ebma** [comment]
@pendulum-chain/product this will be required for Nabla launch and is also relevant for [this](https://github.com/pendulum-chain/tasks/issues/56) ticket.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/14?planning-poker) with Zenhub @adelarja @b-yap @ebma @TorstenStueber

**Comment by prayagd** [comment]
Thanks @ebma for creating this ticket
