### ISSUE TITLE
Subscription feature for Mykobo to subscribe to the Pendulum Indexer for transaction tracking on Pendulum

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum-squids#19]
Develop a subscription feature that allows Mykobo to subscribe to the Pendulum Indexer so the transactions on Pendulum can be tracked

Acceptance Criteria:
The Pendulum Squid is deployed to Aquarium and accessible
The subscription feature for external parties is implemented
Document the subscription API or mechanism for external parties.

## Technical considerations
The implementation should be done using the GraphQL subscriptions, which are documented for subsquid [here](https://docs.subsquid.io/graphql-api/subscriptions/).

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/312?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
@annatekl please move this ticket to the pendulum-squids repository instead.

**Comment by prayagd** [comment]
@adelarja are you currently working on this ticket? If yes can you please move it to development?
