### ISSUE TITLE
Add example url for deployed squids in the README

### ISSUE THREAD

**Issue by adelarja** [pendulum-chain/pendulum-squids#27]
The example script we provided for subscribing to events in our squids works well when running locally. However, it can be a bit difficult to obtain the correct URL for subscribing to one of our deployed squids.

Here are the subscription URLs for our production squids:

"wss://squid.subsquid.io/foucoco-squid/graphql"
"wss://squid.subsquid.io/pendulum-squid/graphql"
"wss://squid.subsquid.io/amplitude-squid/graphql"

We could add them to the README so that they are easily accessible when needed.

**Comment by prayagd** [comment]
@ebma i assume this is low priority right?

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/27?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
It is indeed. But it's so easy to do, that I'd say we just do it anyways. It would take like 10 minutes to do it.

**Comment by prayagd** [comment]
@ebma Perfect quick win, moving it to Ready.

**Comment by prayagd** [comment]
Already made the change, Please review
