### ISSUE TITLE
Update the indexer to provide metadata/tags added with setRemark()

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum-squids#30]
### Context
When subscribing to the indexer to monitor events like off ramp transaction, the stablecoin issuer has a need to track a reference number associated with transactions during the off-ramp process.

### Requirement

Update the indexer to also provide metadata/tags added with setRemark()  for executed transfers.

### Technical considerations

Unlike on Stellar, it's not possible to add a 'memo' to transfers by default. Nevertheless, we can achieve something similar by grouping calls to `tokens/balances::transfer()` and `system::remark()` extrinsic into the same transaction. Thus, we assume that users who want to attach reference numbers to their transfers group the calls to transfer and set a remark in a `utility::batch()` or `utility::batchAll()` extrinsic.

Thus, we need to change the indexer such that for every transfer that is [handled](https://github.com/pendulum-chain/pendulum-squids/blob/1cd1a27efdbe0f2ba45161f0ac39ecad0d6a2aa3/src/mappings/token.ts#L421), we also check if the same transaction contains a call to `system::remark()` and if so, include the contained data into the `Transfer` entity stored by the indexer.

**Comment by annatekl** [comment]
@ebma can you please add the technical requirements for this ticket?

**Comment by ebma** [comment]
This ticket should be moved to the pendulum-squids repository.

**Comment by annatekl** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/30?planning-poker) with Zenhub @b-yap

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/30?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
@pendulum-chain/product this ticket should get high prio once estimated.
