### ISSUE TITLE
Add info about basic general blockchain components to indexer

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#31]
Our indexer currently does not offer much 'general' data. You cannot query the last blocks, extrinsics or events. The base version that is deployed in combination with the archive already exposes this data, see e.g. [here](https://foucoco.explorer.subsquid.io/graphql). The code for that 'base squid' is [here](https://github.com/subsquid-labs/giant-squid-explorer).
Sometimes we do need to have access to this basic data. For example, solving https://github.com/pendulum-chain/tasks/issues/60 requires it.

## TODO
We should extend the schema of our squids to also offer data about:
- blocks
- extrinsics
- calls
- events

We should **not** add the `metadata` as it takes too much space and we will never query it from these indexers. 

The implementation should draw heavy inspiration from the implementation of the [giant-squid](https://github.com/subsquid-labs/giant-squid-explorer). We should:
- adopt the necessary entities from the [schema](https://github.com/subsquid-labs/giant-squid-explorer/blob/main/schema.graphql)
- regenerate the types and models
- adopt the fields that are defined in [processor.ts](https://github.com/subsquid-labs/giant-squid-explorer/blob/main/src/processor.ts) and add the processing defined [here](https://github.com/subsquid-labs/giant-squid-explorer/blob/a3d9b4f08ecbd918f18c87fc715e742cbdf145c4/src/main.ts#L6) to our processor as well

**Comment by ebma** [comment]
@pendulum-chain/product This task is related https://github.com/pendulum-chain/tasks/issues/60. It will change the indexer to offer the data that we need for https://github.com/pendulum-chain/tasks/issues/60

**Comment by prayagd** [comment]
@bogdanS98 is see you already have started working on it? Can you please add your estimates to the ticket?
