### ISSUE TITLE
Only process price info updates for the latest blocks

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#34]
At the moment, the syncing of our squids is significantly slowed down by processing price update events. Since we don't care about historic prices but on every block, we just overwrite the latest price, we can speed this up by only processing these events if the current block is the 'head' of our chain.

**Comment by ebma** [comment]
@pendulum-chain/product this ticket is just a nice-to-have feature but yields significant improvements to the syncing speed of our indexers, so I recommend we work on this very soon.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/34?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
