### ISSUE TITLE
Finish and test Zenlink implementation

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#4]
Although we already added some changes to our indexers to support Zenlink, we never actually tried if it works in practice because we were not really able to interact with the Zenlink pallet yet.

## TODO 
- [x] Create a pool/pair on Foucoco's Zenlink pallet
- [ ] Check that the related events are properly processed by the indexer. If that's not the case, add the required changes

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/4?planning-poker) with Zenhub @adelarja @ebma @TorstenStueber

**Comment by vadaynujra** [comment]
@adelarja @ebma is the first task in the to-do list completed?
Also, looking at the issues blocking this one, will the PR 241 require a runtime upgrade on Amplitude?

**Comment by ebma** [comment]
> is the first task in the to-do list completed?

Yes, it is.

> Also, looking at the issues blocking this one, will the PR 241 require a runtime upgrade on Amplitude?

Yes, it will.
