### ISSUE TITLE
Update farming types and investigate farming event processing errors

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#41]
The pendulum squid is currently reusing the farming-related types and events from foucoco. This is because the farming pallet was not live on Pendulum at the time we created the squid. We should change that.

Besides that, there are some errors shown on the Amplitude squid when starting it from scratch.
```
Error processing event 'Farming.Claimed'. Skipping due to error: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
```
It might be that these errors are also thrown due to incorrect type conversions and are fixed by regenerating types. 

## TODO
- Regenerate the types for pendulum based on latest archive metadata 
- Fix the `AssertionError` thrown by the amplitude squid

**Comment by ebma** [comment]
@pendulum-chain/product this is also required for the Zenlink UI integration because otherwise our squid would show inaccurate data for Pendulum farming pools.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/41?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
