### ISSUE TITLE
Migrate to new Nabla contracts

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum-squids#44]
The Nabla contracts were changed in [this PR](https://github.com/0xamberhq/contracts/pull/65) and their internal state and abi changed.

The squids should be updated to index the new Nabla contracts.

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/44?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by prayagd** [comment]
@TorstenStueber would this thing has to be done each time Nabla updates their internal state? How frequently the internal states are updated and how do we keep track of these changes? so that we know squids need to be updated

**Comment by TorstenStueber** [comment]
This needs to happen whenever Nabla will be upgraded to a new version with new features, not when the state changes.

**Comment by prayagd** [comment]
@TorstenStueber Can you please update the status here? is this done? should we close?

**Comment by TorstenStueber** [comment]
I close when everything is done and merged.

**Comment by prayagd** [comment]
moving to review as PR linked and reviewers assigned
