### ISSUE TITLE
Fix constants to enable indexing of new pairs and pools

### ISSUE THREAD

**Issue by gianfra-t** [pendulum-chain/pendulum-squids#50]
After the [addition](https://github.com/pendulum-chain/transaction-builder/pull/57) of new swap pairs for Amplitude and Pendulum, we need to make some changes to the hard-coded constants in the processor required to properly index the events.

For instance, [here](https://github.com/pendulum-chain/pendulum-squids/blob/2c892a4cf063ef105dc85ca43b6f91e3ae60d354/src/constants.ts#L19) we need to add all the relevant tokens that are used in the pairs on both chains.

We also need to ensure that relevant types (farming, zenlink) are generated for Pendulum.

Finally, we need to modify the use of the hard-coded `CHAIN_ID` [constant](https://github.com/pendulum-chain/pendulum-squids/blob/2c892a4cf063ef105dc85ca43b6f91e3ae60d354/src/constants.ts#L58) currently pointing to Amplitude.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/50?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by prayagd** [comment]
Very urgent as blocking the Zenlink pools on Amplitude, moved to ready without it being estimated.

**Comment by gianfra-t** [comment]
I pushed a "hotfix" to our squids and now we can see the new pools. But still this needs to be worked and cleaned.
