### ISSUE TITLE
Await database operations

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#55]
The squid on Amplitude is frequently facing errors with

```
too late to perform db updates, make sure you haven't forgot to await on db query
```

which probably happens because we don't `await` the database operations in all functions that interact with the squid `store` object.

## TODO 
Use `await` in functions that interact with the `ctx.store`, e.g. [here](https://github.com/pendulum-chain/pendulum-squids/blob/1a942272345091fdebf32be6ef5d692212de7aee/src/mappings/nabla.ts#L197).
To make sure we don't miss this we can think about adding [this](https://eslint.org/docs/latest/rules/require-await) ESlint rule.

**Comment by prayagd** [comment]
Putting this in maintenance epic
