### ISSUE TITLE
Prices and amount not updated on Zenlink UI for PEN/DOT pool

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum-squids#57]
## Context
After performing some swaps the prices on zenlink UI for both PEN and DOT dont change neither do the amount of tokens in the pool. Expected to change the amount of tokens and the price of the tokens in the pool

## Expected outcome
* Prices of the tokens should update after swapping
* Amount of the tokens should update after swapping

## Reference
![image](https://github.com/pendulum-chain/pendulum-squids/assets/52105313/c80608a7-f0e6-4787-8f5c-0bb39c934505)

**Comment by prayagd** [comment]
cc @gianfra-t

**Comment by gianfra-t** [comment]
@prayagd is it possible to make a similar `DOT -> PEN` swap to check that it is working now? Since the changes are live.
