### ISSUE TITLE
Setup queries for Nabla backend for campaign and mainnet reward program

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum-squids#58]
## Context
As the Nabla testnet is soon would be ready, growth wants to do a airflyft campaign where they want to track the actions user performed during a certain period of time. After the testnet campaign and mainnet launch, we also want to introduce a reward program based on points, where we will track certain KPI and reward user with points. This is to attract LPs.

### Requirement
* Following queries should be available in the Nabla squid
* For testnet campaign, growth wants to track the following actions over a period of 1 week using airlyft
    * If the user did a swap
    * if the user added liquidity to the swap pools
    * If the user added liquidity to the backstop pool
* For the reward program, we want to track the following factors (as of now not decided but probable approach) 
    * Amount LPed (TVL)
    * Duration (for which the amount is LPed)
* Above queries should be available for both Foucoco and Pendulum

### Technical considerations

Currently, we have four entities for Nabla: `Router`, `NablaToken`, `SwapPool` and `BackstopPool`, see [here](https://github.com/pendulum-chain/pendulum-squids/blob/71e97fa96a0a4a272136a31a41312d861df41e5b/schema.graphql#L744-L777). We are not storing data about events like swapping or depositing liquidity. We should:

- Create a new entity `NablaSwap` based on the [Swap](https://github.com/pendulum-chain/pendulum-squids/blob/71e97fa96a0a4a272136a31a41312d861df41e5b/schema.graphql#L475) entity we use already for Zenlink. 

- Create new entities `NablaBackstopLiquidityDeposit` and `NablaSwapLiquidityDeposit` based on the [Mint](https://github.com/pendulum-chain/pendulum-squids/blob/71e97fa96a0a4a272136a31a41312d861df41e5b/schema.graphql#L424-L446) entity
- Create new entities `NablaBackstopLiquidityWithdrawal` and `NablaSwapLiquidityWithdrawal` based on the [Burn](https://github.com/pendulum-chain/pendulum-squids/blob/71e97fa96a0a4a272136a31a41312d861df41e5b/schema.graphql#L448-L473) entity

The new entities should store the relevant general metadata like `id`, `transaction`, `timestamp` and `pair` and then take the other data from the respective event emitted and processed by the indexer. The available events can be seen in the `abi` folder [here](https://github.com/pendulum-chain/pendulum-squids/blob/main/src/abi/swap.ts) and [here](https://github.com/pendulum-chain/pendulum-squids/blob/main/src/abi/backstop.ts).

To derive the values for 'Amount LPed (TVL)' and 'Duration (for which the amount is LPed)' we would then manually (or with a script) compare the `NablaXDeposit` and `NablaXWithdrawal` events for each user to be able to say how many tokens were provided as liquidity and for how long.

**Comment by prayagd** [comment]
Follow up of this [ticket](https://github.com/pendulum-chain/tasks/issues/259)

**Comment by prayagd** [comment]
@pendulum-chain/devs this information enough to setup the queries?

**Comment by ebma** [comment]
I assume you want to be able to filter the 'Amount LPed (TVL)' and 'Duration (for which the amount is LPed)' per user?

This still needs some technical refinement before someone can work on it but I can do that later.

**Comment by prayagd** [comment]
Yes

**Comment by ebma** [comment]
I added the technical considerations for this ticket.

**Comment by TorstenStueber** [comment]
Note that this PR is still open which redefines some of the Nabla related entities: https://github.com/pendulum-chain/pendulum-squids/pull/52#pullrequestreview-1893920980

**Comment by TorstenStueber** [comment]
@ebma How does the `StakePosition` entity for Zenlink work? Just the linked definition of the schema is not enough for me to understand its semantics (without reading the code). Why would that be required in the first place in order to satisfy the requirements of the ticket – seems to me like the other three entities are sufficient.

I also propose to limit the stored data to the absolute necessary to satisfy this ticket, no need to go further if not required at the moment.

**Comment by ebma** [comment]
The `StakePosition` is used by Zenlink's farming pools and is updated each time a user deposits/withdraws some LP from the farming pool.

It's true that it might not be absolutely necessary to have this entity for Nabla based on the requirements of this ticket, as we can also derive it based on the other deposit/withdrawal entities. I'll remove it from the description again.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/58?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
