### ISSUE TITLE
Fix eslint

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum-squids#63]
I observed some errors in the code that would have been easy to prevent with improved linting rules (or linting is set up incorrectly).

This is:
* definition of variables that are not used
* (particularly important): forgetting to await the return result of a function (that returns a promise)

## Context
This configuration change will make some errors less likely.

**Comment by TorstenStueber** [comment]
Seems like the eslint configuration in the project is just outdated and eslint does not work anymore. At least the npm scripts `lint` and `lint:fix` don't work.

**Comment by prayagd** [comment]
@TorstenStueber is this a very high priority one and what is it blocking or what functionality does it enable?

**Comment by TorstenStueber** [comment]
It's a chore to improve code quality and reduce silly errors.

**Comment by gianfra-t** [comment]
Eslint was working for me, so perhaps this was fixed during all this time. Created a [PR](https://github.com/pendulum-chain/pendulum-squids/pull/71) after running `lint:fix`.
