### ISSUE TITLE
Add changes for indexing events of Nabla smart contracts

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#7]
This ticket is related to https://github.com/pendulum-chain/tasks/issues/16.

We want to make sophisticated UIs for interaction with the Nabla smart contracts. In order to do so, we need to collect and transform some historic data emitted my the Nabla smart contracts.
This ticket is about adding these changes to our indexers.

The implementation should draw heavy inspiration from [this](https://github.com/0xamberhq/subgraph-mumbai) existing implementation of an indexer for Nabla.

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/7?planning-poker) with Zenhub @adelarja @TorstenStueber

**Comment by ebma** [comment]
@pendulum-chain/product I created this ticket as a follow-up/replacement to [this](https://github.com/pendulum-chain/tasks/issues/16) one since unfortunately, it's not possible to move tickets. I think we can close the task ticket and consider it replaced by this one.

**Comment by TorstenStueber** [comment]
@ebma can you elaborate what historic data we would need to collect or is this about all historic data?

**Comment by ebma** [comment]
I did not add details about the events needing to be processed nor the schema because I think all that should become clear when looking at the code of the other indexer implemented by/for Nabla (https://github.com/0xamberhq/subgraph-mumbai). We can assume that we have to provide the same data since IIRC they use that to develop their other UIs for Ethereum.
